#***************************************************************************
# Copyright (c) 2021 for information on the respective copyright owner
# see the NOTICE file and/or the following repository:
#     https://github.com/boschglobal/automotive-bus-schema
#
# SPDX-License-Identifier: Apache-2.0
#***************************************************************************

---
openapi: 3.0.0
info:
  title: Automotive Bus Signal Interface Data Payloads.
  description: Schemas for MsgPack encoded payloads.
  contact:
    url: https://github.com/boschglobal/automotive-bus-schema
  license:
    name: Apache-2.0
    url: https://github.com/boschglobal/automotive-bus-schema/blob/main/LICENSE
  version: 1.0
components:
  schemas:
    SignalUidList:
      description: Signal UID List
      type: array
      items:
        description: Signal UID
        anyOf:
          - type: integer
          - type: number
    SignalValueList:
      description: Signal Value List
      type: array
      items:
        description: Signal Value
        type: integer
        format: uint32
    SignalData:
      description: MsgPack encoded Signal Data. Number of elements in each nested array should be identical.
      example: Data = [[0..N],[0..N]]
      type: array
      minItems: 1
      maxItems: 2
      items:
        oneOf:
          - $ref: '#/components/schemas/SignalUidList'
          - $ref: '#/components/schemas/SignalValueList'
